### PR TITLE
My files design updates for tab selection

### PR DESCRIPTION
**Pull request by marcelinkaaa**

### CODE REVIEW

**Comment by gubatron** [comment]
Alden, please take a look.
Something tells me there's too much repetition here.

**Comment by aldenml** [comment]
Yes, I don't clearly see of the per type drawable are actually used or no. @marcelinkaaa can you confirm this?

**Comment by marcelinkaaa** [comment]
Do you mean browse_peer_..._selectors and search_peer_..._selectors in drawables? the browse selectors we connected to both the search results page (view_searchinput_radiogroup) and the my_files page (fragment_browse_peer) we connected to browse_peer selectors so I created search_peer_selectors to separate the look as both had different dimensions.

**Comment by aldenml** [comment]
Yes, but one per each file type?

**Comment by marcelinkaaa** [comment]
Yes, each per files type. Just like browse_peer selectors.

**Comment by aldenml** [comment]
Ok, we can cleanup later (for both)

**Comment by gubatron** [comment]
merging then

**Pull request merged**
