### PR TITLE
Updating Spanish Translation after new test

### PR DESCRIPTION
**Pull request by muckachina**
When opening a file the option "Abierto" is not correct, it should be "Abrir".

Also "Borrar las Completadas" sounds rare, the state for finished downloads is "Terminado"

### CODE REVIEW

**Comment by gubatron** [comment]
Thank you so much Mrs.!
black-man-w-tear

**Comment by aldenml** [comment]
Angel, echo eso para atras

**Comment by gubatron** [comment]
revert?

**Comment by aldenml** [comment]
Yes, the merge in the erika's branch change almost all the files. Better she rebase(or similar) or just put the two strings (and send her the BTC).

**Comment by aldenml** [comment]
Force update to this commit https://github.com/frostwire/frostwire-android/commit/6c6feb34825409242637982021c79ae4b3c04dc0 (your tag)

**Pull request merged**
