### PR TITLE
[WIP] Urdu Translations

### PR DESCRIPTION
**Pull request by amingilani**
Translating strings to Urdu (ur)

### CODE REVIEW

**Comment by gubatron** [comment]
thank you for getting this started, let's add at least 50% of the translation before we merge these commits.

**Comment by amingilani** [comment]
Yes, yes, apologies, it's just that I plan on doing these a few at a time, whenever I get around to them. I opened this PR incase someone wants to pick up the pace.. @mannantirmizi

**Comment by gubatron** [comment]
sweet!

Glad to have you. Thanks so much for the initiative.

**Comment by mannantirmizi** [comment]
I'm in! I'll get started properly after the next week. Exams danglin' like
a sword.

**Comment by gubatron** [comment]
hi there, don't forget about us, there's bitcoin in the tip4commit fund as a nice bonus to your contribution.

**Comment by amingilani** [comment]
Thank you for the reminder @gubatron. Quick question, tell me how to get my own branch running on my Nexus 10? Urdu is a right-to-left language, and I'd like to test this PR before the merge. I use Ubuntu.

**Comment by gubatron** [comment]
you can run it from an IDE like IntelliJ or you can build the apk like this:

`./gradlew assembleDebug`

the resulting .apk files that you can install on your android device will be at `build/outputs/apk` inside the `frostwire-android` folder.

**Pull request merged**
